### PR TITLE
add necessary + relevant files prior to CRAN submission

### PR DESCRIPTION
**Pull request by rrrlw**
- [x] `cran-comments.md` in preparation for submission
- [x] `NEWS.md` (completed in #15)
- [x] `CONTRIBUTING.md`
- [x] `CODE_OF_CONDUCT.md`
- [x] `DESCRIPTION` dependencies updated

Edit:
- [x] added pkgdown site
- [x] add [tdaunif](https://github.com/corybrunson/tdaunif/) to `Suggests` and incorporate a more exotic manifold sample into the PH vignette
- [ ] visual regression tests
- [x] drop `theme_tda`

### CODE REVIEW

**Comment by rrrlw** [comment]
Thanks @corybrunson for adding NEWS.md in #15 and for introducing me to the Contributor Covenant (v2 included in this repo) - I'll be sure to switch other repos' contribution guidelines + code of conduct soon. I adapted CONTRIBUTING.md from ggalluvial.

Quick note: I added our emails to CODE_OF_CONDUCT.md and used your gmail from DESCRIPTION. If you'd prefer a different email, please edit.

Currently, just awaiting R CMD check results from win-builder (r-devel). No problems w/ it on Travis (Linux), AppVeyor (Windows), or local install (Mac) w/ r-release.

I will update this PR once win-builder results are back and request a formal review (by @corybrunson) prior to merging.

**Comment by corybrunson** [comment]
@rrrlw my email is fine as and where it is!

**Comment by rrrlw** [comment]
Just added the `cran-comments.md` file to the `cran-submit` branch - please feel free to add any other local, rhub, etc. test environments.

Adding code coverage and tdaunif are the last two tasks prior to initial CRAN submission, correct?

**Comment by corybrunson** [comment]
I think so!

**Comment by rrrlw** [comment]
* fixed a couple merge conflicts
* PRNG for author order ended up alphabetical, switched in vignettes (arbitrary method, happy to adjust based on your preference)
* updated pkgdown website
* updated README.Rmd & corresponding output (default persistence diagram layout has changed)

**Comment by rrrlw** [comment]
Looks like the checklist is complete - what are the steps remaining to complete prior to merging & submitting to CRAN?

**Comment by rrrlw** [comment]
@corybrunson apologies if we've discussed this and I've forgotten - I'm seeing 23 skipped tests on my local machine. Is this expected behavior?

**Comment by corybrunson** [comment]
@rrrlw most of the skipped tests are visual regression tests, preceded in the test files by `skip_on_travis()` and `skip_on_appveyor()` because the templates to which the tests match the plots (located in `tests/figs`) are `.gitignore`d. I don't remember if we or i meant for this to be temporary or permanent! Certainly we can make the change on a sub-branch and see how the services handle it. Do you want to make the attempt?

**Comment by rrrlw** [comment]
Happy to give it a shot

**Comment by corybrunson** [comment]
@rrrlw i was just using the documentation to guide an experiment with the README and realized that the documentation for the geoms does not include sections on recognized aesthetics. [The documentation for `ggplot2::geom_linerange()`](https://ggplot2.tidyverse.org/reference/geom_linerange.html) is a good example. For ggalluvial, i have [a roxygen2 template for this section](https://github.com/corybrunson/ggalluvial/blob/main/man-roxygen/geom-aesthetics.r) that populates the documentation for each geom, but we'd need at least two here (one for the persistence layers, one for the point cloud layers). I expect that many ggplot2 users are used to looking for aesthetic info in this section, so i'd suggest adding it to the geoms' documentation before submitting to CRAN.

I'd be glad to leave this to you if you want to try it out. Or i could probably get to it this coming week.

**Comment by rrrlw** [comment]
I'll give this a shot over the next few days and request your review on the PR when ready, good catch!

**Pull request merged**
