### PR TITLE
visual regression tests

### PR DESCRIPTION
**Pull request by corybrunson**
Hey @rrrlw, i just learned about the **vdiffr** package and tried it out on the simplicial complex layers. It works very well, though is still in development. If you're OK with using it, take a look and accept this PR (or make changes). I plan to return later to enrich the barcode and persistence diagram tests, but i'll wait for your signal.

### CODE REVIEW

**Comment by corybrunson** [comment]
Update: Forgot that i'd branched off `readme` rather than `master`. Only requesting PR into `readme`.

**Comment by rrrlw** [comment]
Looks interesting, but the AppVeyor and Travis CI checks are all failing (looks like for the same reason - the added test). Is this a known error for vdiffr?

A quick side note: would you mind if I add the *.svg files created in the test directory to the project's gitignore file? It doesn't look like they need to be version controlled as they'd be recreated if users run the tests locally. Let me know!

**Comment by corybrunson** [comment]
Ergh, yes, sorry about that. Leave the PR open for now, and i'll give this a couple more tries.

Maybe the `.svg` files can be ignored; i expect that'll depend on whether the **vdiffr** tests should be run on the continuous integration services or only on our own machines. We'll see!

**Comment by corybrunson** [comment]
The solution, i think, is simply to skip the **vdiffr** tests on the CI services. If it's cool with you, i'll incorporate more of these tests into the `vdiffr` branch and ask your blessing on the PR once that's all working.

**Comment by rrrlw** [comment]
That sounds good, but before you go through all the effort, could you use either rhub or win-builder to confirm that the vdiffr tests pass on them? Since they mimic CRAN’s systems, if vdiffr tests fail on them we will likely run into problems submitting to CRAN. I will do the same and let you know if it passes.

**Comment by corybrunson** [comment]
Good idea — yes, i will.

**Comment by corybrunson** [comment]
`devtools::check_rhub()` produces no errors with the new tests. I tried both with and without adding `tests/figs` to `.Rbuildignore`. I'll admit that i don't completely understand the process here, as i don't have the bandwidth right now to dig into the **vdiffr** source code. I'm keen to know if you hit any snags i didn't.

Looking forward: It would be easy to remove these tests later if we want; they live inside function-specific expectation blocks. But i'm also OK with keeping them on a separate branch for now, even as we merge other branches into `master`. What are your thoughts?

**Comment by rrrlw** [comment]
I would be willing to merge the tests into master, would love to have them in the first CRAN version of ggtda. If CRAN submission does produce spurious errors like Travis and AppVeyor CIs did, then we can separate the vdiffr tests from master. Does that seem reasonable?

**Comment by corybrunson** [comment]
Hey, sorry for the delay. This all sounds good. I'll wait until i've implemented **vdiffr** testing for the other plot layers to submit a PR into `master`. And i'll go ahead and delete the `vdiffr` branch next time i work on this, probably Sunday. Thanks!

**Comment by corybrunson** [comment]
Actually, want me to leave, e.g., the barcode geoms for you to write visual regression tests for? It's a fun experience and you might want to use it in other packages that involve plot production.

**Pull request merged**
