### PR TITLE
pkg: remove TDAstats dependency

### PR DESCRIPTION
**Pull request by corybrunson**
Note: In a few places, data sets previously called from TDAstats are now generated from scratch. This code is a bit clunky, but most of it can be replaced by [tdaunif](https://github.com/corybrunson/tdaunif/) samplers once that package is also on CRAN.

### CODE REVIEW

**Comment by rrrlw** [comment]
Looks like `ripserr` not being on CRAN is messing up the CIs - will keep a reminder to look at this PR once ripserr makes it on CRAN? (likely w/in a week)

**Comment by corybrunson** [comment]
Righto!

**Comment by rrrlw** [comment]
Resolved conflict in DESCRIPTION and moved ggplot2 to Depends from Imports (as discussed on Slack), currently awaiting CRAN response for ripserr

**Comment by corybrunson** [comment]
On reflection, i should have committed the most recent changes (which follow from the change of ggplot2 from imports to depends) to `master`. Sorry about that!

**Review by rrrlw — COMMENTED** [review]
Code looks good to me!

Although it technically does not belong in the `unimport` branch, would you be okay w/ me commenting out the Cech complex stuff in this PR? (see vignette simplicial.Rmd where Vietoris-Rips and Cech complex for equilateral triangle both look same, even thought they shouldn't - I think we'd chatted about this a while back)

**Comment by corybrunson** [comment]
Is the plan to exclude the `*_cech()` layers from a first release or to fix them ahead of it? I was hoping for the latter and can prioritize the fix if it's urgent!

**Comment by rrrlw** [comment]
I'm okay w/ either option, let's aim for the latter. I don't see a reason for urgency, no need to rush! And please let me know if/how I can help.

**Review by rrrlw — APPROVED** [review]
`stat_cech*` was fixed in #23 (thank you @corybrunson!), can merge this branch at your convenience (ofc, after we fix any merge conflicts caused by #23)

**Comment by corybrunson** [comment]
Sorry @rrrlw but i want to make sure not to mix something up: Which PR should we merge first? I'll see about the unexpected check failures in #23 .

**Comment by rrrlw** [comment]
I think merging either first is fine! Although we might have to merge master back into the second PR we merge and/or fix merge conflicts. Either way, I don’t think it should be an issue.

Re: the failing check in #23, looks like it’s just a slight decrease in code coverage (other 5 tests look okay), which should be okay?

**Comment by corybrunson** [comment]
We've plenty of time before submission to CRAN, so i'm not too concerned. : )

**Comment by rrrlw** [comment]
Hm, I was kinda hoping to submit to CRAN sooner rather than later (but not urgently) to get ggtda out there and have TDAstats  (and potentially other tda-verse packages) Import it. Definitely no rush, but let's touch base about it at our next chat?

**Comment by corybrunson** [comment]
You're right, that was poor phrasing. My thinking is on the order of weeks, not months.

I had honestly not known what "code coverage" meant, so i just looked it up and explored the codecov checks. Very helpful, in particular to have the specific objects highlighted that are not yet tested! I think i can take care of these next weekend, or i'm glad to leave them to you.

**Comment by rrrlw** [comment]
Sounds good re: submission timeline. Looks like `persistence.R` is where code coverage needs to be increased; as you're more familiar w/ the code, I'd feel more comfortable w/ you adding coverage where it's reasonable. Does that sound okay? (the weekend sounds good if that still works)

**Comment by corybrunson** [comment]
> Edit: probably in a new branch?

Indubitably.

**Pull request merged**
