### PR TITLE
Merge cran-prep into master

### PR DESCRIPTION
**Pull request by rrrlw**
Major change = second vignette (simplicial.Rmd)
A few minor changes (see commits below, happy to expand on specific ones as necessary).

Changes are in preparation for submission of ggtda to CRAN. I believe we are holding submission to JOSS until Shiny functionality is added. @corybrunson, would love your feedback on the changes whenever you get time - thanks! Please feel free to edit the cran-prep branch directly as well.

### CODE REVIEW

**Comment by corybrunson** [comment]
@rrrlw the vignette looks good so far. At one point it points out that the different parameters `radius` (of `stat_disk()`) and `diameter` (of `stat_vietoris*()` and of `stat_cech*()`) may cause confusion. Would it be better to allow both parameters to be passed to both stats? We could still use different parameters in the vignette for illustrative purposes.

**Comment by rrrlw** [comment]
That works! I think the uses of radius and diameter are pretty intuitive the way they're set up right now as well, so I'm open to whichever option you prefer.

**Comment by corybrunson** [comment]
OK cool. The vignette finale is neat! Maybe it could be titled something like "Persistence, Punctuated" since the goal is to use fixed diameters to build intuition about persistence over a continuously varying diameter. : )

**Comment by rrrlw** [comment]
I like it! If you haven’t already, feel free to update the title.

Any changes that I should make before you merge this? I am unsure if it matters in which order convenience or cran-prep are merged into master; what do you think?

**Comment by corybrunson** [comment]
I don't think it should matter, except that we remember to reset the 2-dimensional vdiffr test anchors. Are you ready to merge both into `master`? Want me to do that and handle whatever conflicts arise (none should)?

**Comment by rrrlw** [comment]
Sure! Should we work on the warnings returned by devtools::test() in master once both branches have been merged?

**Comment by corybrunson** [comment]
Agreed—are you still getting errors on this branch after updating the vdiffr figures? Either way, i think it's safe to move everything to `master` and handle things there. I'll do a first pass now.

**Comment by corybrunson** [comment]
@rrrlw done! I'll leave it to you to close this PR and delete the branches if everything checks out on your end.

**Comment by rrrlw** [comment]
Fantastic, thank you @corybrunson! All looks good - I will do a last check when I’m at a computer just to make sure.

**Comment by rrrlw** [comment]
Committed a couple of changes to fix issues in R CMD check, otherwise all looks good! Deleting the `cran-prep` branch now

**Pull request merged**
