### PR TITLE
drop theme_tda

### LINKED ISSUE #35: drop theme_tda
While reviewing the exported objects, i noticed that `theme_persist()` is a copy of `theme_tda()`. Since there will eventually be many more plot layers, some of which may be better suited to theme elements different from those of persistence diagrams, i would suggest dropping the generically-named `theme_tda()` in favor of defining only more precise themes as needed.

If agreed to, it would be good to do this as part of #21, to avoid future deprecation.

### PR DESCRIPTION
**Pull request by rrrlw**
fixes #35

### CODE REVIEW

**Comment by corybrunson** [comment]
The revision makes sense and checks run fine on my machine. Some of the documentation needs to be updated. My usual step at this point is to [search for the removed object name in all files](https://support.rstudio.com/hc/en-us/articles/200710523-Navigating-Code), make changes in appropriate files (e.g. `README.Rmd`), and then run updates (e.g. `devtools::document()`) to disseminate those changes (e.g. to `README.md`).

**Comment by rrrlw** [comment]
Good catch! Just committed a few more changes - how does it look now?

**Comment by corybrunson** [comment]
Good, i think! Though we'll still want to do a final rebuild of the pkgdown website immediately before submission.

**Comment by corybrunson** [comment]
Shoot, sorry again @rrrlw—i keep confusing our responsibilities; i meant to approve, not to merge.

**Comment by rrrlw** [comment]
All good! Saved me a step

**Pull request merged**
