### PR TITLE
fix(stat_cech2): correct & refactor proximate_triples() + update examples, tests

### PR DESCRIPTION
**Pull request by corybrunson**
The Čech 2-complex stat (`stat_cech2()`) is corrected from its earlier miscalculated form. The problem lay in the internal function `proximate_triples()`. The examples and tests are updated to reflect the correction.

I don't expect this to conflict with other branches in progress, but i thought it was substantive enough to warrant a separate branch.

Sorry about that! Thanks for the prompt to get back to this.

### CODE REVIEW

**Review by rrrlw — APPROVED** [review]
Wow, I hope I eventually develop a comparable work ethic - thanks for the quick return! The fix looks good to me, merge at your convenience.

**Comment by corybrunson** [comment]
This was my excuse to take a break from writing! I sort of hope no one ever looks closely at the old code, which was not only wrong but used way more steps than necessary (to determine whether the triangle formed by three points is obtuse; i had dug in on the cosine formula and forgotten the diagonal theorem). Come to think of it, i also forgot to remove an unexported helper function. Hooray for late-night commits.

**Comment by corybrunson** [comment]
@rrrlw since the PR has complete code coverage, shall we merge it and open an issue to add unit testing for uncovered code (assuming that's something we want to be sure to do before CRAN)?

**Comment by rrrlw** [comment]
Sounds good to me! Greater than 80% coverage also seems sufficient, but we can definitely take a look before CRAN submission

**Pull request merged**
