### PR TITLE
pkg: add tdaunif to suggests + use projective plane in ph vignette

### PR DESCRIPTION
**Pull request by corybrunson**
NOTE: ggtda functionality does not depend on tdaunif, which is used to generate
example point clouds. Rather, experimental workflows may use manifold samples
from tdaunif, as illustrated in the vignette and possibly future documentation.

### CODE REVIEW

**Comment by rrrlw** [comment]
Would it be possible/reasonable to merge this into cran-submit? Repeatedly merging main into cran-submit has produced the same merge conflicts a few times (maybe we could branch off of cran-submit instead? Idk what the best workflow is)

**Comment by corybrunson** [comment]
@rrrlw switched the "merge into" branch to `cran-submit`! (Is there a name for the target branch of a PR, by the way?)

**Comment by corybrunson** [comment]
@rrrlw and the commit conflicts should be resolved—we'll see in a moment.

By the way, there's some technical and theoretical math in the revised vignette. Because the package is geared toward data analysts rather than mathematicians, i think should either be dropped/simplified or augmented with a bit of explanation. Do you agree, and do you have a preference between the two?

**Comment by rrrlw** [comment]
I think target branch of PR is the base branch - will take a look at vignette soon for the suggestion above. Thanks for the merge conflict fix and base branch adjustment!

**Comment by rrrlw** [comment]
just looked at phom.Rmd and simplicial.Rmd in the tdaunif branch - which parts do you think should be revised?

**Comment by corybrunson** [comment]
In `phom`, i'm looking at two places:

- the characterization of the real projective plane's homology using the binary field
- the interpretation of the "primary" and "secondary" (my terms) persistent features

Users should have at least some intuitive grasp of persistent homology, so perhaps they can be expected to roll with these discussions and look up elsewhere what they don't understand? Or should they be made clearer for non-specialists?

**Comment by rrrlw** [comment]
> * the characterization of the real projective plane's homology using the binary field

It appears that this is primarily used in describing the sample dataset. I think that's okay b/c the 4x4 plot grid gives a good intuition of point cloud shape and b/c data analysts would still understand the software based on the rest of the text. Maybe one additional sentence stating the same concept(s) in layperson's terms if necessary?

> * the interpretation of the "primary" and "secondary" (my terms) persistent features

As someone who hasn't formally studied the field, I don't have a strong opinion here. I think the terms "primary" and "secondary" make intuitive sense so I'd be happy to keep them. However, if these terms are already defined w/ different meanings, we could switch them.

**Comment by corybrunson** [comment]
> It appears that this is primarily used in describing the sample dataset. I think that's okay b/c the 4x4 plot grid gives a good intuition of point cloud shape and b/c data analysts would still understand the software based on the rest of the text. Maybe one additional sentence stating the same concept(s) in layperson's terms if necessary?

OK, i'll try this out.

> As someone who hasn't formally studied the field, I don't have a strong opinion here. I think the terms "primary" and "secondary" make intuitive sense so I'd be happy to keep them. However, if these terms are already defined w/ different meanings, we could switch them.

Ah, i wasn't so worried about the terms (my parenthetical note was just to clarify that they're not standard) but rather about the clarity of my interpretation. There's one clearly most persistent feature in the dimension we expect, then less persistent but still outlying features in all three dimensions computed. So i thought it proper to explain them away, and i wonder if the explanation works.

**Comment by rrrlw** [comment]
IMO, the explanation works!

**Comment by corybrunson** [comment]
Thanks! Made some revisions to it anyway, plus several corrections or adjustments throughout that i didn't catch the first time (most due to changes i'd made). Ready to merge on your approval. : )

**Comment by rrrlw** [comment]
added min version of tdaunif - is that okay? (i realize that there's only one version that's been on CRAN, i added it just for the consistency and as a reminder for when future versions are released)

**Review by rrrlw — APPROVED** [review]

**Pull request merged**
